### ISSUE TITLE
Feature request: custom or softer colors for containers

### ISSUE THREAD

**Issue by lifostack** [B-i-t-K/PwnFox#11]
Loving the extension, tho sometimes the colors are a bit 'grating' on the eyes, would love to put some softer or customer colors in that are easier on the eyes.

Thank you for designing this extension for us!

**Comment by B-i-t-K** [comment]
The colors are fixed in Burpsuite, I can't change them.

With [Sharpener](https://portswigger.net/bappstore/3c5025b0e19d419a8f339ee0c30391dd) You might be able to change them. It also include some settings to work with pwnfox, replacing the burp side of pwnfox
