### ISSUE TITLE
Cannot load extension

### ISSUE THREAD

**Issue by 0xEval** [B-i-t-K/PwnFox#2]
Hi @B-i-t-K , I get the following error when trying to load the extension:

![image](https://user-images.githubusercontent.com/19994887/84464229-87232f00-aca6-11ea-9277-17268b49708a.png)

Read in the following post [](https://www.vanstechelman.eu/content/solution-javalangclassnotfoundexception-when-loading-your-burp-suite-extention) that it could be due to the way it was packaged but after unzipping it, it seems to have the proper structure.

Thanks for the help

**Comment by B-i-t-K** [comment]
The old compilation script had a bug.
Use the release jar or compile it with intellij
