### ISSUE TITLE
No Icon shown in toolbar

### ISSUE THREAD

**Issue by mtausig** [B-i-t-K/PwnFox#21]
I am having a problem with newer versions of firefox. While the add-on is properly installed and visible on the *Add-ons and themes* page, no status icon is displayed in the toolbar. In consequence, I cannot activate it or open a new container.

I have observed this behaviour on Firefox 115(ESR) on Kali Linux and Firefox 117 on Windows 10.

No error messages are printed in the console, not even when inspecting the add-on vie `about:debugging`.

**Comment by B-i-t-K** [comment]
I can't reproduce the issue,

are you sure you have "pin to toolbar" selected ?

![image](https://github.com/yeswehack/PwnFox/assets/4963842/5f2b79ef-d5da-4fdb-846c-00784eddd6d7)

**Comment by mtausig** [comment]
Thank you, that does indeed solve the problem.
Is it expected behaviour, that you have to manually perform this step? This wasn't required previously.

**Comment by B-i-t-K** [comment]
It's a firefox thing, not a pwnfox one. I guess you need to ask mozilla :p

**Comment by mtausig** [comment]
For reference: [Explanation by Mozilla on the topic](https://support.mozilla.org/en-US/questions/1412248)
