### ISSUE TITLE
Color tab don't working anymore

### ISSUE THREAD

**Issue by rext49612** [B-i-t-K/PwnFox#23]
hey i'm using this coloring the tab functionality ,but i don't see any color in burp proxy i reinstall/reconf everything in both win64/linux seems not working any more can you confirm is this issue only on my side?

**Comment by serialfuzzer** [comment]
The problem is browser extension is not sending the header 'x-pwnfox-color' anymore. When I intercept the request and set the 'X-Pwnfox-Color' header manually, the request is highlighted in HTTP History. Tested on : Firefox

**Comment by rext49612** [comment]
Thank you for your reply, i use match and replace burp add/replace feature to append this header but it still not showing any colors in history tab  ,testing some access control issue it's hard to do without color tabs. I think developer need to quick fix this  asap.

**Comment by B-i-t-K** [comment]
Thanks for the report, 
The burp part of pwnfox might be outdated. While waiting for a patch you can use [Sharpener](https://portswigger.net/bappstore/3c5025b0e19d419a8f339ee0c30391dd), there is an option to support PwnFox

**Comment by serialfuzzer** [comment]
Thank you for the information! Hope this issue gets patched soon

**Comment by rext49612** [comment]
Thank you for creating this useful extension and providing alternative , ty gentleman adios..
