### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dark-warlord14** [B-i-t-K/PwnFox#3]
Thank you for this extension. It is awesome.

Actual Feature Request
-----------------

Can you add a feature where we can rename the profile name as we like?
e.g. While testing with multi-accounts if we can rename the profiles with the username like admin-user, not-admin-user, etc It will help in testing. 
Will love to know your thoughts on this?

Thank you.

**Comment by B-i-t-K** [comment]
It is possible to change the name of a container in firefox, here : about:preferences#containers
PwnFox only check that the name starts with "PwnFox-"

https://github.com/B-i-t-K/PwnFox/blob/ad692de9526ad04b75bf0c80e7079d3673489428/firefox/src/features.js#L85

But keep in mind that the button will always create PwnFox-blue,red,yellow . If you want to open a custom container just make a long click on the new tab button, a list of container should appear.

I didn't find a way to include this feature in pwnfox while keeping the UI clean.
If you find a way to do it, I can include it in the next realease.

**Comment by dark-warlord14** [comment]
Thank you for your suggestions. In the meanwhile, let's close this.
