### ISSUE TITLE
Remove the color header in adress bar

### ISSUE THREAD

**Issue by 0xJs** [B-i-t-K/PwnFox#6]
Is it possible to remove the Pwnfox-Pink text and picture from the address bar?

![afbeelding](https://user-images.githubusercontent.com/43987245/113271202-8bbedf80-92da-11eb-9ff8-d0219009eaa6.png)

Tried checking the preferences and options in Firefox but couldn't find it.

**Comment by B-i-t-K** [comment]
This is added by Firefox, not by pwnfox. Try looking in firefox settings instead.
But I don't think there is an easy way to remove it sorry
