### ISSUE TITLE
Bug(Maybe??)

### ISSUE THREAD

**Issue by ghost** [B-i-t-K/PwnFox#7]
Great tool,

In Burp Suite 2021.4, the proxy history is no longer being colorized.
Could it be the Burp Suite version??

![pwnfox](https://user-images.githubusercontent.com/70813379/113476887-eb59ee00-9486-11eb-8717-036e4a23fe44.png)

**Comment by Smismi11** [comment]
I have the same issue. The extension is useless now :(

**Comment by entroPyth** [comment]
Confirmed no colorizing in HTTP history on BurpSuite v2021.4.2

**Comment by B-i-t-K** [comment]
I'll take a look tomorrow

**Comment by B-i-t-K** [comment]
Fixed in v1.0.3 please download the new PwnFox.jar from release

**Comment by entroPyth** [comment]
Thank you!
