### ISSUE TITLE
Not showing color in new burp 2021.5.1

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [B-i-t-K/PwnFox#9]
Hello Team,

I have updated my burp to the latest version i.e 2021.5.1 and I am on firefox 88.0. When I create  a new container I don't see the color differentiation. 

Can you please help on this

**Comment by Cyb3rGh0st786** [comment]
Thanks, I did not see the new version with the fix and it is working fine

**Comment by MPaandeey** [comment]
How to update to new version
